name: Flowzone

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - "main"
      - "master"

jobs:
  flowzone:
    name: Flowzone
    uses: product-os/flowzone/.github/workflows/flowzone.yml@master
    secrets:
      FLOWZONE_TOKEN: ${{ secrets.FLOWZONE_TOKEN }}
      BALENA_API_KEY: ${{ secrets.BALENA_API_KEY }}
    with:
      toggle_auto_merge: false
      balena_slugs: |
        gh_klutchell/wireguard-amd64,
        gh_klutchell/wireguard-aarch64,
        gh_klutchell/wireguard-armv7hf
